services:
  spark-master:
    build: .
    image: spark-custom
    container_name: spark-master
    command: /opt/spark/bin/spark-class org.apache.spark.deploy.master.Master
    environment:
      - SPARK_MASTER_HOST=spark-master
      - PYSPARK_PYTHON=python3.13
    ports:
      - "8080:8080"
      - "7077:7077"
    restart: always
    networks:
      hadoopnet:
        ipv4_address: 172.28.1.10

  spark-worker-1:
    pull_policy: never
    image: spark-custom
    container_name: spark-worker-1
    command: /opt/spark/bin/spark-class org.apache.spark.deploy.worker.Worker spark://spark-master:7077
    environment:
      - SPARK_WORKER_CORES=${WORKER_CORES}
      - SPARK_WORKER_MEMORY=${WORKER_MEMORY}
    ports:
      - "8081:8081"
    depends_on:
      - spark-master
    restart: always
    networks:
      hadoopnet:
        ipv4_address: 172.28.1.11

  spark-worker-2:
    pull_policy: never
    image: spark-custom
    container_name: spark-worker-2
    command: /opt/spark/bin/spark-class org.apache.spark.deploy.worker.Worker spark://spark-master:7077
    environment:
      - SPARK_WORKER_CORES=${WORKER_CORES}
      - SPARK_WORKER_MEMORY=${WORKER_MEMORY}
    ports:
      - "8082:8081"
    depends_on:
      - spark-master
    restart: always
    networks:
      hadoopnet:
        ipv4_address: 172.28.1.12

  spark-worker-3:
    pull_policy: never
    image: spark-custom
    container_name: spark-worker-3
    command: /opt/spark/bin/spark-class org.apache.spark.deploy.worker.Worker spark://spark-master:7077
    environment:
      - SPARK_WORKER_CORES=${WORKER_CORES}
      - SPARK_WORKER_MEMORY=${WORKER_MEMORY}
    ports:
      - "8083:8081"
    depends_on:
      - spark-master
    restart: always
    networks:
      hadoopnet:
        ipv4_address: 172.28.1.13

networks:
  hadoopnet:
    external: true
    name: hadoop_hadoopnet
