FROM apache/spark:4.1.1

USER root

# Instalar Python 3.13 y hacerlo el python3 por defecto
# para coincidir con la versión del driver (Jupyter)
RUN apt-get update && \
    apt-get install -y software-properties-common && \
    add-apt-repository -y ppa:deadsnakes/ppa && \
    apt-get update && \
    apt-get install -y python3.13 && \
    apt-get clean && rm -rf /var/lib/apt/lists/* && \
    update-alternatives --install /usr/bin/python3 python3 /usr/bin/python3.13 1 && \
    update-alternatives --set python3 /usr/bin/python3.13

ENV PYSPARK_PYTHON=python3.13
ENV PYSPARK_WORKER_PYTHON=python3.13

USER spark
