services:
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    restart: always
    ports:
      - "3000:3000"
    environment:
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: grafana # ¡Usad contraseñas seguras en producción!
      GF_INSTALL_PLUGINS: hadesarchitect-cassandra-datasource
    volumes:
      - grafana-data:/var/lib/grafana
    networks:
      hadoopnet:
        ipv4_address: 172.28.1.35

volumes:
  grafana-data:

networks:
  hadoopnet:
    external: true
    name: hadoop_hadoopnet
